.bash/functions: Print more errors on fail

diff --git a/.bash/functions b/.bash/functions
--- a/.bash/functions
+++ b/.bash/functions
@@ -172,7 +172,8 @@ mynettest ()
   mylocalip
 
   echo -n "Nameserver: "
-  grep "^nameserver" /etc/resolv.conf | cut -d ' ' -f 2-
+  NAMESERVER=$(grep "^nameserver" /etc/resolv.conf | cut -d ' ' -f 2-)
+  [ -z "${NAMESERVER}" ] && say fail "Fail" || echo "${NAMESERVER}"
 
   echo -n "Net IP: "
   mynetip
